apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-inference
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mortadha1996/llm-inference-platform.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
